name: Performance Benchmarks

on:
  push:
    branches: [ DevBranch ]
    paths:
      - 'Pulsar4X/GameEngine/**'  # Only trigger on changes to GameEngine

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: |
        cd Pulsar4X/Benchmarks
        dotnet build -c Release
        
    - name: Run benchmarks
      run: |
        cd Pulsar4X/Benchmarks
        dotnet run -c Release --filter '*'
        
    - name: Store benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: Pulsar4X/Benchmarks/BenchmarkDotNet.Artifacts/results
